### ISSUE TITLE
Unexpected output format in VSCode terminal

### ISSUE THREAD

**Issue by markpattison** [haf/expecto#331]
Using VSCode 1.35.1 on Windows 7 with Ionide 4.0.0.

The same issue happens with `cmd` or `powershell` terminal options.

#### To reproduce:

`dotnet new -i Expecto.Template::*
dotnet new expecto -n exp
dotnet restore
dotnet run`

#### Actual output (sample):

`←[30;1mExpecto Running... ←[1000D←[0m←[?25l←[30;1mExpecto Running... ←[1000D←[0m←[?25l←[30;1mExpecto Running... 3/8 /←[1000D←[0m←[?25l                        ←[1000D←[?25h←[37m[←[37m16:05:35 ←[37mINF←[37m] ←[37mEXPECTO? Running tests...←[37m ←[37m<←[37mExpecto←[37m>←[37m
←[0m←[37m[←[37m16:05:35 ←[31mERR←[37m] ←[36msamples/I'm always fail (should fail)←[37m failed in ←[32m00:00:00.0110000←[37m. ←[36m
This was expected...
   at Tests.tests@19-3.Invoke(Unit _arg4) in E:\Prog\Source\test\Sample.fs:line 20
   at Expecto.Impl.execTestAsync@935-1.Invoke(Unit unitVar) in C:\Users\Anthony Lloyd\src\expecto\Expecto\Expecto.fs:line 939
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Async.StartChild@1641-5.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)←[37m ←[37m<←[37mExpecto←[37m>←[37m
←[0m←[37m[←[37m16:05:35 ←[31mERR←[37m] ←[36msamples/when true is not (should fail)←[37m failed in ←[32m00:00:00.0110000←[37m. ←[36m
I should fail because the subject is false. Actual value was false but had expected it to be true.
   at Tests.tests@12-1.Invoke(Unit _arg2) in E:\Prog\Source\test\Sample.fs:line 14
   at Expecto.Impl.execTestAsync@935-1.Invoke(Unit unitVar) in C:\Users\Anthony Lloyd\src\expecto\Expecto\Expecto.fs:line 939
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at <StartupCode$FSharp-Core>.$Async.StartChild@1641-5.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)←[37m ←[37m<←[37mExpecto←[37m>←[37m
←[0m←[37m[←[37m16:05:35 ←[31mERR←[37m] ←[36msamples/contains things (should fail)←[37m failed in ←[32m00:00:00.0350000←[37m. ←[36m`

#### Expected output:

Something like ![this](https://github.com/haf/expecto/blob/master/docs/sample-output-2.png).

**Comment by AnthonyLloyd** [comment]
It sounds like the terminal isn;t supporting colours for some reason. Not sure why maybe a Windows 7 thing? To work around set --colours 0.

**Comment by markpattison** [comment]
The terminal colours do work from FAKE though...

**Comment by AnthonyLloyd** [comment]
It must not support ANSI colours and FAKE is using Console.ForegroundColor instead.

Colours are a bit of a pain to support and why we had to put in the --colours option. We could put in and option to use Console colours but they are not atomic and end up with bugs were the colour isn't reset correctly at the end.

**Comment by haf** [comment]
I would much prefer the check if it's running on Windows; if you want you can do a change that even looks as the windows version. But I don't believe in mutilating the output of this library just so that a decade old operating system can avoid the above issues; especially since you @markpattison could install ANSI colours https://github.com/adoxa/ansicon and have it working.

**Comment by haf** [comment]
See https://github.com/haf/expecto/issues/315 for more discussions.

**Comment by AnthonyLloyd** [comment]
@haf It's such a mess and so difficult to test. I fear checking TTY takes us further down the rabbit hole. It would be good to have a solid example of covering multiple platforms and consoles.

**Comment by haf** [comment]
@AnthonyLloyd Perhaps then we start with https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=netframework-4.8 ? Windows can default to 0 colours, otherwise 256?

**Comment by Lanayx** [comment]
Same issue in full Visual Studio plugin, makes it unsusable :(
![image](https://user-images.githubusercontent.com/3329606/60626943-0b153b80-9df5-11e9-967d-e2816d1435e7.png)

**Comment by AnthonyLloyd** [comment]
@Lanayx use --colours 0 if that's possible via the plugin

**Comment by Lanayx** [comment]
@AnthonyLloyd Unfortunately there is no such option there

**Comment by Lanayx** [comment]
By the way, I have the same issue as topic starter when running dotnet test on windows 10

**Comment by AnthonyLloyd** [comment]
@Lanayx I think you need to raise with adamchester/expecto-adapter maybe they should offer config or just set to --colours 0 if VS doesn't support colours. For dotnet test it would be YoloDev/YoloDev.Expecto.TestSdk.

**Comment by Michael-McD** [comment]
There's also a stacktrace from Expecto itself that make it difficult to read.  E.g.:

```
  at Expecto.Impl.execTestAsync@692-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at <StartupCode$FSharp-Core>.$Async.StartChild@1650-5.Invoke(AsyncActivation`1 ctxt) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1650
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
```

**Comment by theshadowbrokerss** [comment]
As mentaioned by @haf https://github.com/haf/expecto/issues/331#issuecomment-507163272 ANSICON  working fine for me.

#### To Setup ANSICON:

1. Download [ANSICON ](https://github.com/adoxa/ansicon)
2. Then rename the folder to ANSICON and move it to C:\
3. Modify the following in VSCode settings:

```
{
    ....

     "terminal.integrated.shell.windows": "C:\\Program Files\\ANSICON\\x64\\ansicon.exe",
     "terminal.integrated.shellArgs.windows": [
         "C:\\Program Files\\Git\\bin\\sh.exe",
         "--login",
         "-i"
     ]

}
```
